// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/atomic_swap/v1/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SwapPacketData defines a struct for the packet payload
type SwapPacketData struct {
	// the token denomination to be swapped
	SendingTokenDenom string `protobuf:"bytes,1,opt,name=sending_token_denom,json=sendingTokenDenom,proto3" json:"sending_token_denom,omitempty"`
	// the token amount to be swapped
	SendingTokenAmount string `protobuf:"bytes,2,opt,name=sending_token_amount,json=sendingTokenAmount,proto3" json:"sending_token_amount,omitempty"`
	// the token denomination to be swapped for
	ReceivingTokenDenom string `protobuf:"bytes,3,opt,name=receiving_token_denom,json=receivingTokenDenom,proto3" json:"receiving_token_denom,omitempty"`
	// the token amount to be swapped for
	ReceivingTokenAmount string `protobuf:"bytes,4,opt,name=receiving_token_amount,json=receivingTokenAmount,proto3" json:"receiving_token_amount,omitempty"`
	// the sender address
	Sender string `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	// the sender address on the destination chain
	SenderReceivingAddress string `protobuf:"bytes,6,opt,name=sender_receiving_address,json=senderReceivingAddress,proto3" json:"sender_receiving_address,omitempty"`
	// the counterparty address on the destination chain
	ExpectedCounterpartyAddress string `protobuf:"bytes,7,opt,name=expected_counterparty_address,json=expectedCounterpartyAddress,proto3" json:"expected_counterparty_address,omitempty"`
}

func (m *SwapPacketData) Reset()         { *m = SwapPacketData{} }
func (m *SwapPacketData) String() string { return proto.CompactTextString(m) }
func (*SwapPacketData) ProtoMessage()    {}
func (*SwapPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e225b3c72fc646b1, []int{0}
}
func (m *SwapPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapPacketData.Merge(m, src)
}
func (m *SwapPacketData) XXX_Size() int {
	return m.Size()
}
func (m *SwapPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_SwapPacketData proto.InternalMessageInfo

func (m *SwapPacketData) GetSendingTokenDenom() string {
	if m != nil {
		return m.SendingTokenDenom
	}
	return ""
}

func (m *SwapPacketData) GetSendingTokenAmount() string {
	if m != nil {
		return m.SendingTokenAmount
	}
	return ""
}

func (m *SwapPacketData) GetReceivingTokenDenom() string {
	if m != nil {
		return m.ReceivingTokenDenom
	}
	return ""
}

func (m *SwapPacketData) GetReceivingTokenAmount() string {
	if m != nil {
		return m.ReceivingTokenAmount
	}
	return ""
}

func (m *SwapPacketData) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SwapPacketData) GetSenderReceivingAddress() string {
	if m != nil {
		return m.SenderReceivingAddress
	}
	return ""
}

func (m *SwapPacketData) GetExpectedCounterpartyAddress() string {
	if m != nil {
		return m.ExpectedCounterpartyAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*SwapPacketData)(nil), "ibc.applications.atomic_swap.v1.SwapPacketData")
}

func init() {
	proto.RegisterFile("ibc/applications/atomic_swap/v1/packet.proto", fileDescriptor_e225b3c72fc646b1)
}

var fileDescriptor_e225b3c72fc646b1 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0xc2, 0x30,
	0x1c, 0xc6, 0x19, 0x2a, 0xc6, 0x1e, 0x4c, 0x2c, 0x48, 0x96, 0x18, 0xa7, 0xf1, 0xe4, 0x41, 0x56,
	0x11, 0x4d, 0xbc, 0x78, 0x00, 0x79, 0x00, 0x83, 0x26, 0x26, 0x5e, 0x96, 0xae, 0xfb, 0x07, 0x1b,
	0xd8, 0xda, 0xb4, 0x65, 0xc8, 0x5b, 0xf8, 0x58, 0x1e, 0x39, 0x7a, 0x34, 0xf0, 0x06, 0x3e, 0x81,
	0x59, 0x37, 0x70, 0x70, 0x6b, 0xf3, 0xfb, 0x7e, 0xff, 0xef, 0xf0, 0xa1, 0x2b, 0x1e, 0x32, 0x42,
	0xa5, 0x1c, 0x73, 0x46, 0x0d, 0x17, 0x89, 0x26, 0xd4, 0x88, 0x98, 0xb3, 0x40, 0x4f, 0xa9, 0x24,
	0x69, 0x9b, 0x48, 0xca, 0x46, 0x60, 0x7c, 0xa9, 0x84, 0x11, 0xf8, 0x8c, 0x87, 0xcc, 0x2f, 0xa7,
	0xfd, 0x52, 0xda, 0x4f, 0xdb, 0x17, 0xbf, 0x55, 0x74, 0xf8, 0x3c, 0xa5, 0xf2, 0xc9, 0x5a, 0x7d,
	0x6a, 0x28, 0xf6, 0x51, 0x5d, 0x43, 0x12, 0xf1, 0x64, 0x18, 0x18, 0x31, 0x82, 0x24, 0x88, 0x20,
	0x11, 0xb1, 0xeb, 0x9c, 0x3b, 0x97, 0x07, 0x83, 0xa3, 0x02, 0xbd, 0x64, 0xa4, 0x9f, 0x01, 0x7c,
	0x8d, 0x1a, 0x9b, 0x79, 0x1a, 0x8b, 0x49, 0x62, 0xdc, 0xaa, 0x15, 0x70, 0x59, 0xe8, 0x5a, 0x82,
	0x6f, 0xd0, 0xb1, 0x02, 0x06, 0x3c, 0xdd, 0xee, 0xd8, 0xb1, 0x4a, 0x7d, 0x0d, 0x4b, 0x2d, 0xb7,
	0xa8, 0xb9, 0xed, 0x14, 0x3d, 0xbb, 0x56, 0x6a, 0x6c, 0x4a, 0x45, 0x53, 0x13, 0xd5, 0xb2, 0x7e,
	0x50, 0xee, 0x9e, 0x4d, 0x15, 0x3f, 0x7c, 0x8f, 0xdc, 0xfc, 0x15, 0xfc, 0x1f, 0xa5, 0x51, 0xa4,
	0x40, 0x6b, 0xb7, 0x66, 0x93, 0xcd, 0x9c, 0x0f, 0x56, 0xb8, 0x9b, 0x53, 0xdc, 0x43, 0xa7, 0xf0,
	0x21, 0x81, 0x19, 0x88, 0x02, 0x96, 0x75, 0x80, 0x92, 0x54, 0x99, 0xd9, 0x5a, 0xdf, 0xb7, 0xfa,
	0xc9, 0x2a, 0xf4, 0x58, 0xca, 0x14, 0x37, 0x7a, 0xaf, 0x5f, 0x0b, 0xcf, 0x99, 0x2f, 0x3c, 0xe7,
	0x67, 0xe1, 0x39, 0x9f, 0x4b, 0xaf, 0x32, 0x5f, 0x7a, 0x95, 0xef, 0xa5, 0x57, 0x79, 0x7b, 0x18,
	0x72, 0xf3, 0x3e, 0x09, 0x7d, 0x26, 0x62, 0xc2, 0x84, 0x8e, 0x85, 0x26, 0x3c, 0x64, 0xad, 0xa1,
	0x20, 0xe9, 0x1d, 0x89, 0x45, 0x34, 0x19, 0x83, 0xce, 0xd6, 0xd7, 0xa4, 0xd3, 0x6e, 0xe5, 0x53,
	0xb6, 0xec, 0xf0, 0x66, 0x26, 0x41, 0x87, 0x35, 0xbb, 0x7a, 0xe7, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x04, 0x1b, 0xb4, 0x8b, 0x25, 0x02, 0x00, 0x00,
}

func (m *SwapPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExpectedCounterpartyAddress) > 0 {
		i -= len(m.ExpectedCounterpartyAddress)
		copy(dAtA[i:], m.ExpectedCounterpartyAddress)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ExpectedCounterpartyAddress)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SenderReceivingAddress) > 0 {
		i -= len(m.SenderReceivingAddress)
		copy(dAtA[i:], m.SenderReceivingAddress)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.SenderReceivingAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReceivingTokenAmount) > 0 {
		i -= len(m.ReceivingTokenAmount)
		copy(dAtA[i:], m.ReceivingTokenAmount)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ReceivingTokenAmount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ReceivingTokenDenom) > 0 {
		i -= len(m.ReceivingTokenDenom)
		copy(dAtA[i:], m.ReceivingTokenDenom)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ReceivingTokenDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SendingTokenAmount) > 0 {
		i -= len(m.SendingTokenAmount)
		copy(dAtA[i:], m.SendingTokenAmount)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.SendingTokenAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SendingTokenDenom) > 0 {
		i -= len(m.SendingTokenDenom)
		copy(dAtA[i:], m.SendingTokenDenom)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.SendingTokenDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SwapPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SendingTokenDenom)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.SendingTokenAmount)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ReceivingTokenDenom)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ReceivingTokenAmount)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.SenderReceivingAddress)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ExpectedCounterpartyAddress)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SwapPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendingTokenDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendingTokenDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendingTokenAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendingTokenAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivingTokenDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceivingTokenDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivingTokenAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceivingTokenAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderReceivingAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderReceivingAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedCounterpartyAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExpectedCounterpartyAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
