// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: ibc/applications/swap/v1/packet.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FungibleTokenSwapPacketData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// tokens on supply chain, e.g.: 100000000uatom
	SupplyToken string `protobuf:"bytes,1,opt,name=supply_token,json=supplyToken,proto3" json:"supply_token,omitempty"`
	// tokens on demand chain, e.g.: 500000000uosmo
	DemandToken string `protobuf:"bytes,2,opt,name=demand_token,json=demandToken,proto3" json:"demand_token,omitempty"`
	// the sender address
	SendAddress string `protobuf:"bytes,3,opt,name=send_address,json=sendAddress,proto3" json:"send_address,omitempty"`
	// the recipient address on the demand chain to received the receive_token
	AddressToReceiveDemandToken string `protobuf:"bytes,4,opt,name=address_to_receive_demand_token,json=addressToReceiveDemandToken,proto3" json:"address_to_receive_demand_token,omitempty"`
	// the address on the demand chain
	CounterPartyAddress *string `protobuf:"bytes,5,opt,name=counter_party_address,json=counterPartyAddress,proto3,oneof" json:"counter_party_address,omitempty"`
}

func (x *FungibleTokenSwapPacketData) Reset() {
	*x = FungibleTokenSwapPacketData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_applications_swap_v1_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FungibleTokenSwapPacketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FungibleTokenSwapPacketData) ProtoMessage() {}

func (x *FungibleTokenSwapPacketData) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_swap_v1_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FungibleTokenSwapPacketData.ProtoReflect.Descriptor instead.
func (*FungibleTokenSwapPacketData) Descriptor() ([]byte, []int) {
	return file_ibc_applications_swap_v1_packet_proto_rawDescGZIP(), []int{0}
}

func (x *FungibleTokenSwapPacketData) GetSupplyToken() string {
	if x != nil {
		return x.SupplyToken
	}
	return ""
}

func (x *FungibleTokenSwapPacketData) GetDemandToken() string {
	if x != nil {
		return x.DemandToken
	}
	return ""
}

func (x *FungibleTokenSwapPacketData) GetSendAddress() string {
	if x != nil {
		return x.SendAddress
	}
	return ""
}

func (x *FungibleTokenSwapPacketData) GetAddressToReceiveDemandToken() string {
	if x != nil {
		return x.AddressToReceiveDemandToken
	}
	return ""
}

func (x *FungibleTokenSwapPacketData) GetCounterPartyAddress() string {
	if x != nil && x.CounterPartyAddress != nil {
		return *x.CounterPartyAddress
	}
	return ""
}

var File_ibc_applications_swap_v1_packet_proto protoreflect.FileDescriptor

var file_ibc_applications_swap_v1_packet_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x62, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x69, 0x62, 0x63, 0x2e, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x76,
	0x31, 0x22, 0x9f, 0x02, 0x0a, 0x1b, 0x46, 0x75, 0x6e, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x6d, 0x61,
	0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x44, 0x0a, 0x1f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x5f, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x1b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x37, 0x0a, 0x15, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x13, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x72, 0x74, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x69, 0x62, 0x63, 0x2d, 0x67, 0x6f, 0x2f,
	0x76, 0x34, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f,
	0x33, 0x31, 0x2d, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ibc_applications_swap_v1_packet_proto_rawDescOnce sync.Once
	file_ibc_applications_swap_v1_packet_proto_rawDescData = file_ibc_applications_swap_v1_packet_proto_rawDesc
)

func file_ibc_applications_swap_v1_packet_proto_rawDescGZIP() []byte {
	file_ibc_applications_swap_v1_packet_proto_rawDescOnce.Do(func() {
		file_ibc_applications_swap_v1_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_ibc_applications_swap_v1_packet_proto_rawDescData)
	})
	return file_ibc_applications_swap_v1_packet_proto_rawDescData
}

var file_ibc_applications_swap_v1_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ibc_applications_swap_v1_packet_proto_goTypes = []interface{}{
	(*FungibleTokenSwapPacketData)(nil), // 0: ibc.applications.swap.v1.FungibleTokenSwapPacketData
}
var file_ibc_applications_swap_v1_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ibc_applications_swap_v1_packet_proto_init() }
func file_ibc_applications_swap_v1_packet_proto_init() {
	if File_ibc_applications_swap_v1_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ibc_applications_swap_v1_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FungibleTokenSwapPacketData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ibc_applications_swap_v1_packet_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ibc_applications_swap_v1_packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_applications_swap_v1_packet_proto_goTypes,
		DependencyIndexes: file_ibc_applications_swap_v1_packet_proto_depIdxs,
		MessageInfos:      file_ibc_applications_swap_v1_packet_proto_msgTypes,
	}.Build()
	File_ibc_applications_swap_v1_packet_proto = out.File
	file_ibc_applications_swap_v1_packet_proto_rawDesc = nil
	file_ibc_applications_swap_v1_packet_proto_goTypes = nil
	file_ibc_applications_swap_v1_packet_proto_depIdxs = nil
}
